name: tanster
favicon: null
layout_spectrum: 0.62603
typography_spectrum: 0.63392
title: tanster in progress
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4624446399975568
  lightness: 0.816430727019906
  saturation: 0.20702161663211882
  rhythmicContrast: 0.7229402677621692
purpose: []
